EXPERIMENT:
    ID: TARL

TRAIN:
    LR: 0.02
    MAX_EPOCH: 50
    BATCH_SIZE: 8
    BATCH_ACC: 4
    NUM_WORKERS: 4
    N_GPUS: -1
    FREEZE_MODULES: []
    #FREEZE_MODULES: ['BACKBONE','SEM_HEAD','INS_HEAD']
    AUG: True
    SUBSAMPLE: True
    PERCENT: 1.0

MODEL:
    DATASET: KITTI

POST:
    ALG: MEANSHIFT
    BANDWIDTH: 1.2
    MIN_CLUSTER: 50 #10 for nuscenes

LOSS:
    SEM:
        WEIGHTS: [2,6] #Ce, Lovasz

KITTI:
    PATH: data/kitti
    CONFIG: datasets/semantic-kitti.yaml
    NUM_CLASSES: 20 #Get from yaml
    IGNORE_LABEL: 0
    SPACE: # coord limits
        [[-48.0,48.0],[-48.0,48.0],[-4.0,1.5]]
    MIN_VOLUME_SPACE: [3,'-pi',-3]
    MAX_VOLUME_SPACE: [50,'pi',1.5]
    MINI: False
    SUB_NUM_POINTS: 80000

NUSCENES:
    PATH: data/nuscenes
    CONFIG: datasets/semantic-nuscenes.yaml
    NUM_CLASSES: 17 #Get from yaml
    IGNORE_LABEL: 0
    SPACE: # coord limits
        [[-50.0,50.0],[-50.0,50.0],[-5.0,3]]
    MIN_VOLUME_SPACE: [0,'-pi',-5]
    MAX_VOLUME_SPACE: [50,'pi',3]
    MINI: False
    SUB_NUM_POINTS: 50000
